packages:
  - "apps/*"
  - "libs/*"
  - "libs/*/*"
allowBuilds:
  nx: true
  "@swc/core": true
  esbuild: true
  unrs-resolver: true
  "@parcel/watcher": true
  less: true
  "@nestjs/core": false
  sharp: true
  core-js: true
  "@scarf/scarf": false
  msgpackr-extract: true
overrides:
  "postcss@<8.5.23": "8.5.23"
  "nanoid@<3.3.17": "3.3.17"
  "sharp@<0.35.0": "0.35.0"
  "find-my-way@<=9.6.0": "9.7.0"
  "brace-expansion@>=4.0.0 <5.0.9": "5.0.9"
  "js-yaml@>=4.0.0 <4.3.1": "4.3.1"
  "js-yaml@>=5.0.0 <5.2.2": "5.2.2"
  "@fastify/static@<=10.1.1": "10.1.2"
  "exceljs>uuid": "11.1.1"
peerDependencyRules:
  allowedVersions:
    "@fastify/static": "^10.0.0"
